apiVersion: apps/v1
kind: Deployment
metadata:
  name: okyun22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okyun22
  template:
    metadata:
      labels:
        app: okyun22
    spec:
      containers:
      - image: okteto.dev/okyun22:latest
        name: okyun22
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "78d587ea-bf4e-4def-a4c1-c3d34ca98107"
        - name: Vless_Path
          value: "/vl880"
        - name: Vmess_UUID
          value: "78d587ea-bf4e-4def-a4c1-c3d34ca98107"
        - name: Vmess_Path
          value: "/vm990"
        - name: Share_Path
          value: "/v2link"
