apiVersion: v1
kind: Service
metadata:
  name: okyun22
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okyun22"
    port: 8080
  selector:
    app: okyun22
